<x-layouts.dashboard :title="'Kelola Event'">
<div class="space-y-5">
    <div class="flex items-center justify-between"><h2 class="text-lg font-semibold">Semua Event</h2><a href="{{ route('admin.events.create') }}" class="px-4 py-2 bg-coral text-white rounded-lg text-sm font-semibold">Tambah Event</a></div>
    <form method="GET" action="{{ route('admin.events.index') }}" class="flex flex-col sm:flex-row gap-3">
        <input name="search" value="{{ request('search') }}" placeholder="Cari event..." class="flex-1 px-4 py-2.5 rounded-lg bg-navy-surface border border-navy-border text-sm">
        <select name="status" onchange="this.form.submit()" class="px-4 py-2.5 rounded-lg bg-navy-surface border border-navy-border text-sm"><option value="">Semua status</option>@foreach(['upcoming'=>'Akan datang','ongoing'=>'Berlangsung','completed'=>'Selesai','canceled'=>'Dibatalkan'] as $key => $label)<option value="{{ $key }}" @selected(request('status') === $key)>{{ $label }}</option>@endforeach</select>
        <select name="category_id" onchange="this.form.submit()" class="px-4 py-2.5 rounded-lg bg-navy-surface border border-navy-border text-sm"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id') == $category->id)>{{ $category->name }}</option>@endforeach</select>
        <button class="px-5 py-2.5 bg-coral text-white rounded-lg text-sm font-semibold">Cari</button>
    </form>
    <div class="overflow-x-auto rounded-xl border border-navy-border"><table class="w-full text-sm text-left"><thead class="bg-navy-surface text-ink-muted"><tr><th class="px-5 py-3">Judul</th><th class="px-5 py-3">Pengelola</th><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Peserta</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-navy-border">@forelse($events as $event)<tr><td class="px-5 py-4 font-medium">{{ $event->title }}<div class="text-xs text-ink-muted">{{ $event->category->name ?? '-' }}</div></td><td class="px-5 py-4">{{ $event->pengelola->name ?? '-' }}</td><td class="px-5 py-4">{{ $event->start_date->isoFormat('D MMM YYYY') }}</td><td class="px-5 py-4">{{ $event->registrations_count }}/{{ $event->capacity }}</td><td class="px-5 py-4"><div class="flex gap-3"><a class="text-coral" href="{{ route('admin.events.show', $event) }}">Detail</a><a class="text-coral" href="{{ route('admin.events.edit', $event) }}">Edit</a><a class="text-coral" href="{{ route('admin.events.registrations', $event) }}">Peserta</a><form method="POST" action="{{ route('admin.events.destroy', $event) }}" onsubmit="return confirm('Hapus event ini?')">@csrf @method('DELETE')<button class="text-red-400">Hapus</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-ink-muted">Belum ada event.</td></tr>@endforelse</tbody></table></div>
    {{ $events->links() }}
</div>
</x-layouts.dashboard>
